# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Too Many Informations
email: oliviabrundage@gmail.com
description: Learning something new often feels like you being blasted by a fire hydrant. Come share my experience, bit by bit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codemethisolivia.com" # the base hostname & protocol for your site
twitter_username: dothecodeolivia
github_username:  foxiae

# Build settings
markdown: kramdown
